[package]
name = "isle_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isle_engine = { path = "../isle_engine" }
isle_ecs = { path = "../isle_ecs" }
