[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
image = "0.25.2"
isle_math = { path = "../isle_math" }
log = "0.4.22"
wgpu = "22.1.0"
winit = "0.30.5"
